### ISSUE TITLE
Issue with jinja2 and base.html on generating the form

### ISSUE THREAD

**Issue by JmonkG** [CSIRO-enviro-informatics/shacl-form#1]
So, I installed the shacl-form without mayor issues. But when I tried to load the toy example, the moment it tried to generate the form from ttl and I got an issue where base.html was not found. Looking a little into the detail I found that on the rendering folder on the shacl form package those that html template was not copy. Once I copy the template it worked as expected.

**Comment by nicholascar** [comment]
Hi @JmonkG, Do you mean that base.html was in the wrong place? I see that it's in this repo where it should be (inside shaclform/rendering/) so if you cloned this repository to use it, you should have got a copy of it. So where was it missing from?

Thanks, Nick

**Comment by JmonkG** [comment]
Sorry if I wasn't clear on my explanation. I did get the template when I clone it. But then when I installed it to use it, those templates were not copied on the rendering folder, therefore when I used the toy example I got an error of ninja2 didn't found base.html. Maybe it was just a bug on the installation, but when I copied those templates on the installed folder, it worked.

**Comment by nicholascar** [comment]
Oh I see! You mean that the base.htnl file was missing from the folder in the form example repo's templates/ , https://github.com/Laura-Guillory/shacl-form-example/tree/master/view/templates, not from the module repo! Thanks for pointing that out.

I've put the file in there now so this fixes the issue: I've downloaded and run the example just fine now.

Unless there's more to say here, can I close this Issue?

Once again, thanks so much for finding it and letting us know.

**Comment by JmonkG** [comment]
Sure, thank you for taking care of it.

**Comment by nicholascar** [comment]
Just let me know (nick@kirtawong.net) if you are going to continue to work with SHACL Form as we could assist with continued development perhaps.
